### ISSUE TITLE
The Vipps logo should be orange, not green

### ISSUE THREAD

**Issue by cloveras** [Nets-mobile-acceptance/Netaxept-iOS-SDK#1]
Hi - nice work with these SDKs!

I noticed that the Vipps logo is stil green in the screenshots/GIFs, and if you need the orange one, it's here: https://github.com/vippsas/vipps-design-guidelines

Christian, Vipps

**Comment by Miss-PiA** [comment]
Hi @cloveras ,
Thank you for your interest in our SDKs.
You are right, we will update to the latest Vipps orange logo.
We are aiming to the implementation of Vipps in the first quarter of 2019. We will make sure all communication elements are in line with Vipps guidelines by then.
Stay tuned!

Regards,
-Miss PiA

**Comment by Miss-PiA** [comment]
Issue is resolved
