### ISSUE TITLE
Navigation bar bug after dismissing PiaSDKController

### ISSUE THREAD

**Issue by oyvinddd** [Nets-mobile-acceptance/Netaxept-iOS-SDK#10]
Hi,

See screenshots (second one showcasing the bug). After dismissing the PiaSDKController the app always ends up with a solid white color at the top of the screen. Is the SDK applying any global styling (i.e. any appearance proxies) that isn't removed after dismissing? I'm running version 1.3.1.

I'm presenting the controller normally like so:
```
let controller = PiaSDKController(orderInfo: orderInfo, merchantInfo: merchantInfo)
controller.piaDelegate = self
present(controller, animated: true, completion: nil)
```
<img width="457" alt="Screenshot 2019-12-09 at 20 41 01" src="https://user-images.githubusercontent.com/43780301/70466800-3eef3e00-1ac4-11ea-840b-0cf60dd84e03.png">

<img width="500" alt="Screenshot 2019-12-09 at 20 34 29" src="https://user-images.githubusercontent.com/43780301/70466504-92ad5780-1ac3-11ea-8aa5-56d0a7f27950.png">

**Comment by Miss-PiA** [comment]
Hello @oyvinddd 

Thank you for reaching out to us. We will look into the issue and let you know the updates. Our latest version 1.5.1 is out, we would recommend you to implement and check if you face the issue in the latest version as well.

Thank you.

**Comment by Miss-PiA** [comment]
Hello @oyvinddd 

Thank you for your patience. The issue has been fixed on our release 1.5.0, we encourage you to update the SDK to the latest version. We’ll close the issue and please feel free to reach us for further questions.

**Comment by oyvinddd** [comment]
Thanks, @Miss-PiA! I'll update and report back here once I have tested it.

**Comment by oyvinddd** [comment]
I can confirm that this bug has been fixed in the latest version. Thanks.

**Comment by Miss-PiA** [comment]
Hello @oyvinddd 

Thank you for the confirmation and your feedback mean a lot to us.
