### ISSUE TITLE
Commandline builds fail with Pia framework

### ISSUE THREAD

**Issue by mortenholmgaard** [Nets-mobile-acceptance/Netaxept-iOS-SDK#12]
When I run xcode commandline build with fastlane it keeps failing with this error:
> \+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/jl/h0d_w1yx7gjc1gg69q3xmxkr6f01nb/T/gym_config20200227-11584-8gqvio.plist -archivePath /Users/xxx/Library/Developer/Xcode/Archives/xxx/.xcarchive.xcarchive -exportPath /var/folders/jl/h0d_w1yx7gjc1gg69q3xmxkr6f01nb/T/gym_output20200227-11584-1a2d4mf
> 2020-02-27 09:25:14.691 xcodebuild[14452:3912688] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jl/h0d_w1yx7gjc1gg69q3xmxkr6f01nb/T/xxx_2020-02-27_09-25-14.690.xcdistributionlogs'.
> error: exportArchive: IPA processing failed
> Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

When I remove the "Embed Frameworks" Build Phase it succeeds but then the app will crash at startup, just as it does when running from xCode, with this Build Phase missing.

I have included the framework manually just as the guide prescribe. It works fine when building and running from xCode, but we need to be able to send out test version and deploy using CI.

This [post](https://stackoverflow.com/questions/57382217/how-to-fix-ipa-processing-failed-error-in-xcode-11) suggests that it might be a architecture problem in the framework?
I have also looked in to making a [custom runscript](https://medium.com/livefront/how-to-add-a-dynamic-swift-framework-to-a-command-line-tool-bab6426d6c31) to fix this but without success.

[Fastlane](https://github.com/fastlane/fastlane) build command:
```
build_app(scheme: target,
            clean: true,
            configuration: buildConfiguration,
            export_method: "development")
```

**Comment by mortenholmgaard** [comment]
We just found out that adding a Run phase you have in your sample project, solved the problem: 
(or slightly modified)
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script handles Pia framework embedded in the application and
# removes unused architectures. This solves an error archiving the ipa from commandline builds.
# Script found in Netaxept-iOS-SDK PiaSample project.
find "$APP_PATH" -name 'Pia.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

**Please add this info to the setup readme - this is really complicated stuff to figure out!**

**Comment by mathiasemil** [comment]
Thx for this @mortenholmgaard! Had the same issue and would have spend way longer to solve it if it wasn't for this.

Please add this to the readme.

**Comment by Miss-PiA** [comment]
@mathiasemil  Nice to hear that @mortenholmgaard helped you to sort it out. We had created an answer in the FAQ doc in the question 9 from the repository and please check details there:) Let us know if you have any further questions.

**Comment by Miss-PiA** [comment]
The issue has been solved.

**Comment by mortenholmgaard** [comment]
@Miss-PiA Well we never expect a there should be any different in building from the commandline, so I most defently think there should be another Installation readme bullet in the bottom after: "Add Pia.framework to Embedded Binaries from the General tab." refering to the FAQ in question when needing support for commandline build.

**Comment by BuildManager-Nets** [comment]
@mortenholmgaard  thanks for sharing the good suggestion and we will check if we could improve in the coming release. To be clarified, the deliverable framework contains the simulator slices which allow developer to test on simulator. These simulator slices have to be removed before submit app to app store and this script is used to exclude these slices away before you make the build for release to app store.
