### ISSUE TITLE
Unable to input card number for AMEX cards due to logo covering entire input field

### ISSUE THREAD

**Issue by Vasant-Patel** [Nets-mobile-acceptance/Netaxept-iOS-SDK#14]
Issue description:

On iOS when trying to input card number for AMEX card eg: (37XX ....) the logo covers entire input field.

How to reproduce:
To see this issue in production install [VR Matkalla application](https://apps.apple.com/fi/app/vr-matkalla/id1410647394) and select any journey and try paying with new card and input card number starting 37** **** **** **** 

OR

Simply try with` PiaSDKController(orderInfo, merchantInfo) `and input AMEX card number

![IMG_4575CAB02E1E-1](https://user-images.githubusercontent.com/8254593/86914940-ce77d080-c129-11ea-8c40-61565ab2da53.jpeg)

Application is using the flow for card payments with `PiaSDKController` and works fine for other card provider eg: visa / mastercard so it seems iOS sdk is using incorrect asset for AMEX

Issue is reproducible on iOS sdk version 1.4.0

**Comment by Miss-PiA** [comment]
Hi Vasant-Patel 

What is the version of the SDK that you are using ?

**Comment by Vasant-Patel** [comment]
Sdk version is 1.4.0

**Comment by Miss-PiA** [comment]
@Vasant-Patel this issue has already been fixed. Please use the latest version of the SDK.

**Comment by Vasant-Patel** [comment]
yep 1.7.0 seems to work correctly!
