### ISSUE TITLE
Add support for Swift package manager

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#15]
It would be nice to add Swift package manager support as it is clear that this is the way the community is shifting. 
It will also remove the manual / scripting step of moving and unpacking the zip file after it is downloaded through Carthage

https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by Miss-PiA** [comment]
Hello,

Yes, Swift package manager has already been on our radar and will keep you posted once we get support on it! Thanks for your good suggestion!

Regards,
Miss PiA
