### ISSUE TITLE
NPIInterfaceConfiguration -> switchOffTintColor  missing border 

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#16]
Here is a normal switch off stats 
<img width="152" alt="expected off" src="https://user-images.githubusercontent.com/71696542/93884123-c966fe00-fce2-11ea-9ba0-fac7eaa660fa.png">
Here is a normal switch on stats 
<img width="157" alt="expected on" src="https://user-images.githubusercontent.com/71696542/93884175-d8e64700-fce2-11ea-9c29-f7ee33dd149b.png">

If you change the color for the switch in the payment window using **switchOffTintColor** you will end up with below result.
Looks like the border color is also set to white when the  **switchOffTintColor**  is set to white.
<img width="691" alt="SDK off" src="https://user-images.githubusercontent.com/71696542/93884501-42665580-fce3-11ea-89c7-a2dd889054d7.png">

Here is the on state 
<img width="693" alt="SDK on" src="https://user-images.githubusercontent.com/71696542/93884520-4befbd80-fce3-11ea-8066-005d2d3c4978.png">

**Comment by Miss-PiA** [comment]
Hello @sbo-nemlig ,

We will further investigate this issue you reported and get it fixed in the coming release! 

Thanks for your report!

Best regards,
Miss PiA

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig ,

It seems that in this particular use-case, all the three colors - the SDK background color, the switchOffTintColor and the switchThumbColor are set to white. We suggest you adjust the contrasts of these colors to make the switch visible. 

Do you specifically need the border property ? We could take the border color property as a new feature request for our future releases, but cannot promise on the timeline for the same.

**Comment by sbo-nemlig** [comment]
Well we have to set both `switchOnTintColor = .orange` and `switchThumbColor = .white`, as the SDK set the thumb color to a default blue color (Apples is white) 
So someting in the SDK must be removing the shadow and borders when `switchThumbColor`

As you can see from my images the dropshadow is also missing on the "ON" state

**Comment by sbo-nemlig** [comment]
https://stackoverflow.com/questions/47176701/remove-uiswitch-thumb-shadow-effect-swift 

Looks like setting thumbTintColor will remove the shadow. 
Could you remove the blue color you have on the switch now so it just defaults to Apples setup

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig,

We will investigate this further and find a potential solution for this.

**Comment by nets-dev** [comment]
HI @sbo-nemlig ,

We will redesign the UI in the later release and this will be definitely in the scope to be considered. We will keep you updated once the solution is available for you.

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig ,

We will redesigned our UI in the later release and this will definitely in the scope to be changed. We will keep you posted once the solution is available for you to integrate.
