### ISSUE TITLE
Text "Label" is shown for hit about CVV Code 

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#17]
The text "Label" is shown for a short time period before the real text is shown 
![label_payment_checkout MP4](https://user-images.githubusercontent.com/71696542/99939215-d8f9d600-2d69-11eb-8f1d-e9ad5075dba9.gif)

**Comment by Miss-PiA** [comment]
Hey @sbo-nemlig ! 

Thanks a lot for the report! 

We'll take a further look into the issue and get it fixed for an upcoming release. 

Best regards, 
Miss-PiA

**Comment by BuildManager-Nets** [comment]
Fixed in version 2.2.0
