### ISSUE TITLE
Camera view is misplaced on on iPad after changing orientation 

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#18]
When rotating the iPad the camera view is not keeping its constraints, and the view is drawn outside the screen 
![ipad issue mov](https://user-images.githubusercontent.com/71696542/99943491-ad7ae980-2d71-11eb-8de2-8776079a8c5f.gif)

**Comment by Miss-PiA** [comment]
Hey @sbo-nemlig, thanks for catching the issue! 

We'll restrict in the future the application rotation only to portrait mode; and update our documentation to reflect the change. 

Best regards, 
Miss-PiA

**Comment by BuildManager-Nets** [comment]
Fixed in version 2.2.0
