### ISSUE TITLE
Building for iOS, but the linked and embedded framework 'Pia.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by mattiriihimaki** [Nets-mobile-acceptance/Netaxept-iOS-SDK#19]
Hey,

I did like you told on the guide but got that compile error. Any ideas what's wrong?

Pia.framework is Embed & Sign

Xcode 12.3

**Comment by Miss-PiA** [comment]
Hi,

Have you added the run script mentioned in our read me ?

**Comment by mattiriihimaki** [comment]
You mean this one?

```# Type a script or drag a script file from your workspace to insert its path.
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

and yes it below the `Embed Frameworks`

The Sample project it also having the same problem or I'm duplicating the problem on that one.

**Comment by Miss-PiA** [comment]
Hi,

Yes this particular script. Can you please share the exact steps you follow, right from adding the framework in your project to building it.

Also, what is the problem you are facing with the sample app provided ?

**Comment by mattiriihimaki** [comment]
Hei,

The problem that is on the title, the same one, that I have on my own project. Have you tried to run the Sample project with Xcode 12.3?

Download/clone this https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK.git
Unzip PiaSDKFramework.zip to obtain Pia.framework.
Drag and drop Pia.framework to your project.
Go to your project target at Build Phases.
Add Pia.framework to Link Binary With Libraries.
Add Pia.framework to Embedded Binaries from the General tab.

**Comment by Miss-PiA** [comment]
Hi, 

This might be Xcode 12.3 specific issue. Can you try the Xcode 12.2 version ?

Meanwhile, we will investigate this on Xcode 12.3 and get back.

**Comment by ChristianBC** [comment]
Hi,

Just want to mention that the pia framework 2.0.2 compiles in Xcode 12.3 here, by manual installation (following the steps in the readme). 

I'm running into "dyld: Library not loaded: @rpath/Pia.framework/Pia" though, runtime. Not sure if it is related or not, might be configuration issues on my side.

Update: Pia.Framework was Do Not Embed. Setting it to Embed & Sign results in the same compile error (OP title).

Following this thread.

**Comment by mattiriihimaki** [comment]
Hei,

It works on the Xcode 12.2. So something has happened on the Xcode 12.3.

@ChristianBC I have a temporary solution for you. Setting the `Validate Workspace` to `true` on the `Builds Settings` for the `Target`will change the Error to Warning.

**Comment by ChristianBC** [comment]
@mattiriihimaki Yep, that works - thanks for the tip! I still face the runtime _dyld_ issue though. Will await overall investigation by netaxept.

**Comment by Miss-PiA** [comment]
Hi @ChristianBC, 

Can you confirm if you have added the Pia.framework to the Embedded Binaries of the project ? You can verify this in the General tab of the target.

**Comment by ChristianBC** [comment]
Hi @Miss-PiA

Yes, the Pia.framework is there, under Frameworks, Libraries and Embedded Content in the General Tab. And also in the Link Binary With Libraries build phase.

But it was somehow missing in the Embed Frameworks build phase. This seems to remedy the issue.

So with `Validate Workspace` set to true, it compiles and runs on simulator and device. But the Target Integrity warning remains _Building for iOS, but the linked and embedded framework 'Pia.framework' was built for iOS + iOS Simulator_

**Comment by Miss-PiA** [comment]
Hi @ChristianBC , yes, we will investigate the warning on Xcode 12.3.

**Comment by mortenholmgaard** [comment]
@Miss-PiA Any news? - I ran in to the same problem now. 

I have it added all 3 places: Frameworks, Libraries and Embedded Content in the General Tab, Link Binary With Libraries build phase and Embed Frameworks but still gets the problem.

Validate Workspace to true works, but that should only be a temp solution.

**Comment by Miss-PiA** [comment]
Hi @mortenholmgaard, we are still investigating the issue.

**Comment by amnpoosri** [comment]
I can confirm the issue aswell on Xcode 12.3. The workaround for now is seting your Pia.framework to Do not embed (in General > Frameworks, Libraries and Embedded Content)

**Comment by Maddumage** [comment]
Hi, 
I am facing the same issue as mentioned above by @ChristianBC, after updating the Xcode 12.3.
I followed the documentation steps correctly and this worked well in the previous Xcode version.
@Miss-PiA any updates on this.

**Comment by ghost** [comment]
you need to run lipo command manually before first build. The run script never gets executed because this error comes much earlier in the build process. I get this in Xcode 12.4 btw.
edit: dyld: Library not loaded: @rpath/Pia.framework/Pia

edit2: Got it working. Pia.Framework folder needed rename to lowercase Pia.framework. Also i needed to remove it from "Link Binary With Libraries" and only keep the "Embed libraries" (with codesign checkbox) entry.

**Comment by olafandreas-itf** [comment]
This is acually not an issue with Xcode, this is intended to prompt developers to transition to use XCFramework. The feature has gradually been "released" going from a warning to an error.

### Workaround ###
There are multiple workarounds for this, a simple one is:
 `Project -> Build Settings -> Validate Workspace = Yes`.

### Fix ###
Pia.framework should be made available as a XCFramework, I believe this would remove the need for the post-script build phase for the framework also.
https://help.apple.com/xcode/mac/11.4/#/dev544efab96

**Comment by Miss-PiA** [comment]
We have now uploaded [Pia.xcframework](https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/blob/master/Pia.xcframework.zip) containing device and simulator builds. 

Xcode 11+ users can now replace _Pia.framework_ in Xcode-Targets **Frameworks, Libraries and Embedded Contents** 
with XCFramework for iOS and iOS Simulator architectures.

**Comment by Miss-PiA** [comment]
The issue is resolved with XCFramework.
Xcode 11+ users can now replace **Pia.framework** in Xcode-Targets Frameworks, Libraries and Embedded Contents
with **XCFramework** for iOS and iOS Simulator architectures.
