### ISSUE TITLE
 Issue integrating NETS SDK in iOS project.

### ISSUE THREAD

**Issue by PrekshyaBasnet** [Nets-mobile-acceptance/Netaxept-iOS-SDK#2]
**I am having an issue integrating Netaxept SDK in my iOS project.**
**I have latest Carthage version: 0.31.2**
I am trying to install Netaxept SDK using Carthage, after I command `carthage update` I get following error and thus unable to integrate Netaxept in my project.
*** Fetching Netaxept-iOS-SDK
*** Checking out Netaxept-iOS-SDK at "1.1.0"
*** Skipped building Netaxept-iOS-SDK due to the error:
Dependency "Netaxept-iOS-SDK" has no shared framework schemes

**Comment by Miss-PiA** [comment]
Hello @PrekshyaBasnet ,

The result you received when trying to integrate the `Netaxept iOS SDK` in your project is not an error, it's just a warning. This is the lightweight way to use [Carthage](https://github.com/Carthage/Carthage).

However, the PiaSDKFramework.zip should be in Carthage/Checkouts, and should work just fine.

Please let us know if there is anything we can help you with.

Regards,
MissPiA

**Comment by PrekshyaBasnet** [comment]
@Miss-PiA Thank you for your reply. Actually we used Cocoa pod as a dependency manager, since Netaxept does not support pod installation, I was trying the installation through Carthage.
I have followed your step and it is working fine!
Thank you!
