### ISSUE TITLE
Remove save card information switch for Amex

### ISSUE THREAD

**Issue by Lomaas** [Nets-mobile-acceptance/Netaxept-iOS-SDK#21]
Hello!

Question regarding Easy payment and American Express (Amex).

1. As I understand there is an issue with Easy payment and Amex credit card now. Can you confirm this?
2. If so, is it possible to remove the switch for save card information when input of Amex card is detected?
3. Suggestions of other work arounds?

Best regards
Simen

**Comment by Miss-PiA** [comment]
Hello @Lomaas 

Thanks for reaching out to us. We are working on the issue and we will inform you when it has been resolved.

Best regards

**Comment by BuildManager-Nets** [comment]
Hi Lomaas,

The Amex card works well with the Easy Payment. Do you have issues with the same ?
