### ISSUE TITLE
Easy payment fails with error code 102

### ISSUE THREAD

**Issue by ptunde** [Nets-mobile-acceptance/Netaxept-iOS-SDK#22]
Hi,

I'm trying to integrate the Easy payment flow (https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/12-easy-one-click-payment-flow.html) in our production app, using **Option 3: Skip user confirmation - without SDK UI.** 
I'm getting an error after entering the CVV2/CVC2/CID code in the 3DS authentication webpage (screenshot attached):

```
NSError?	domain: "eu.nets.mcommerce.Pia" - code: 102
NSLocalizedDescription" : "The URL can’t be shown"
```

The documentation about the error handling code points to an Internet connectivity issues which is not my case, and the url I'm using for the PiaSDK.initiateTokenizedCardPay method is a valid URL (got from our backend along with the transactionID).

Notes:

> PiA - Netaxept iOS SDK v2.1.0, installed manually using the Pia.xcframework
> running Xcode Version 12.4 on macOS 11.1
> testing on iPhone 8 Simulator and also on an iPhone X (14.4) physical device

<img width="559" alt="Screenshot 2021-02-08 at 12 14 00" src="https://user-images.githubusercontent.com/13233102/107241410-404f2a00-6a2b-11eb-9e00-c6cc35ee48b0.png">

**Comment by ptunde** [comment]
Closing. We found the issue was with our back end, however I think the error message could be a bit more intuitive.

**Comment by TNJ-Logos** [comment]
I'm facing the same issue. I'm wondering how it could be resolved in the backend. Anyone with some insights on this?

**Comment by BuildManager-Nets** [comment]
Hi, 

Can you please describe the error in detail along with screenshots ? Also, what is the version of the iOS SDK that you are using ?

**Comment by TNJ-Logos** [comment]
Hi, 
I'm using the 2.2.0 version of the iOS SDK. It is in Test mode. Installed manually using the Pia.xcframework
running Xcode Version 12.4 on macOS 12.2.3 testing on iPhone 12 Simulator and also on an iPhone Xs (14.4.2) physical device

I'm registrating a payment in the backend.
They can see it and it needs to be completed.
Then I initiate the PiaSDK.initiateTokenizedCardPay call. 
![tokenizedPayment](https://user-images.githubusercontent.com/82457753/114662933-d2103780-9cf9-11eb-9c80-1acf2e7b3edb.PNG)

It is asking for the CVV2 code but after entering that and pressing pay it goes in the failure block giving the NPIErrorCode(rawValue: 102) The URL can’t be shown error.
The redirectUrl is the same as provided during registration. Together with the transactionId and merchantId from the registration response.

What could be causing this error?

**Comment by BuildManager-Nets** [comment]
Can you provide the Merchant Id and the transaction id ?

**Comment by TNJ-Logos** [comment]
MerchantId: xxxxxxxx
TransactionId: d8f199da54fe4150a83f9758ce885eaa

**Comment by BuildManager-Nets** [comment]
We have now enabled trace logs for your merchant id, Please perform one more fresh transaction and send us the transaction id

**Comment by TNJ-Logos** [comment]
TransactionId: 145c87a6c4ed4dc7941255163e8d1654

**Comment by BuildManager-Nets** [comment]
Hi, From logs it seems you are passing serviceType as B. Please pass serviceType as M in the registration call

**Comment by TNJ-Logos** [comment]
Passing serviceType M worked.
