### ISSUE TITLE
Compile warning from Pia.h

### ISSUE THREAD

**Issue by mattiriihimaki** [Nets-mobile-acceptance/Netaxept-iOS-SDK#23]
<img width="1164" alt="Screenshot 2021-02-18 at 8 34 02" src="https://user-images.githubusercontent.com/20223966/108315521-331d0280-71c4-11eb-92d2-d937e53d7c63.png">

Can you fix this as some point as the warning are quite annoying. Thanks.

**Comment by Miss-PiA** [comment]
Hi Matti,

Are you using the native environment or reactNative/Xamarin ? 
Also which verison of the SDK are you using ?
Which version of Xcode are you using ?

**Comment by mattiriihimaki** [comment]
Native
Xcode 12.3
Pia 2.1.0

**Comment by Miss-PiA** [comment]
Hi Matti,

These warnings are appearing for you due to some particular configuration settings in you Xcode, we are not able to reproduce these at our end.
