### ISSUE TITLE
Showing card fees for new cards

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#24]
Hey, 

Is it possible to show any card fees on the payment widow when paying with a new card, like you have for the web version.

**Comment by Miss-PiA** [comment]
Hi,

It is not possible to display the surcharge fee on the card entry UI. Instead, we suggest to use the Getcardinfo call to Netaxept. You can use it on an already saved card so that you can fetch card information leading to surcharge and display the surcharge fee in checkout confirmation screen, prior to initiating the payment.

**Comment by sbo-nemlig** [comment]
Hey, but the issue here is that we don't know what card the user is entering in the view (It is a new payment card) so it could be that a fee is added to the price. Making the price shown on the view wrong / misleading

**Comment by Miss-PiA** [comment]
Hi, this is correct, it is not possible to display the surcharge fee for a new card, this is why we recommend "adding"/"saving" the card first during checkout and then displaying the surcharge fee accordingly, before submitting the payment as a subsequent (Easy flow) transaction.

**Comment by sbo-nemlig** [comment]
But on web it is possible to show it. Could this be a feature that could be added to the SDK in the future ? 

![web](https://user-images.githubusercontent.com/71696542/108996736-0aeb4300-769f-11eb-92a6-152545e59453.png)

**Comment by sbo-nemlig** [comment]
But on web it is possible to show it. Could this be a feature that could be added to the SDK in the future ?

![web](https://user-images.githubusercontent.com/71696542/108997007-687f8f80-769f-11eb-9222-dd059d8ac98f.png)
