### ISSUE TITLE
Cents does not look to be show correctly on the payment button 

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#25]
Steps to reproduce 
1. Using your sample app 
2. Go to `CheckoutController` and change the float amount to 556.55
3. Open payment widow and it only shows 556

![Simulator Screen Shot - iPod touch (7th generation) - 2021-03-04 at 10 21 58](https://user-images.githubusercontent.com/71696542/109941503-85394a00-7cd3-11eb-9957-130a3993083f.png)

**Comment by BuildManager-Nets** [comment]
Hi,

Fixed in the latest v2.1.2 release.
