### ISSUE TITLE
How to make sure 3D package is actually updated to latest

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-iOS-SDK#26]
We recently updated this package on iOS and Android to a version that supports 3D Secure version 2 protocol, since it's required after April 14th.

Now I'm wonder how to make sure the package was actually updated to latest version? I haven't found a way to verify this in the application itself. Payments seem to be going through as usual. Any way to check from package/app what version is actually running? Would be crappy if payments just stopped working on April 14th.

**Comment by Miss-PiA** [comment]
Hi,

You can try to print the below string and check the version number.

`print(Pia.NPIPiaSemanticVersionString);`
