### ISSUE TITLE
The xcframework looks to miss armv7s and arm64 support

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#28]
Looks like the new **xcframework** SDK is missing support for:

* armv7s 

**Simulator**
*  arm64

**Comment by BuildManager-Nets** [comment]
Hi,

It does have the mentioned support.
<img width="367" alt="Screenshot 2021-04-07 at 5 15 10 PM" src="https://user-images.githubusercontent.com/44604698/113861502-ebc6f180-97c4-11eb-823a-608ff3dd86a7.png">

**Comment by sbo-nemlig** [comment]
It should be as in the screenshot below: 
Else you are not supporting M1 mac simulators as you are only support Intel.

Also you are missing **armv7s**  for real devices 

![Skærmbillede 2021-04-07 kl  13 48 50](https://user-images.githubusercontent.com/71696542/113861901-0a6abf80-97a8-11eb-8e63-1544f034e722.png)

**Comment by BuildManager-Nets** [comment]
Hi,

Added missing architectures
