### ISSUE TITLE
Version 2.2.0 not in Nuget?

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-iOS-SDK#29]
Hi there,

I can't seem to find version 2.2.0 in Nuget. 

eu.nets.pia.pia-xamarin-ios is at version 2.0.2

**Comment by BuildManager-Nets** [comment]
Hi,

We would be making the release on Nuget soon. We would keep you posted.

**Comment by BuildManager-Nets** [comment]
Hi,

v2.2.0 is now available on Nuget
