### ISSUE TITLE
Can we create a lib for Flutter?

### ISSUE THREAD

**Issue by iHunterX** [Nets-mobile-acceptance/Netaxept-iOS-SDK#3]
Im creating application with flutter and it will use the Netaxept SDK, for now im trying to create a bridge for that but seem like its not stable enough. Do you guys have plans for implement it in FLutter?

**Comment by Nets-LAKA-Mobile-SDK** [comment]
Hi @iHunterX 
Thank you for your interest in our SDK. 
Flutter is an interesting implementation framework for us, we are studying whether we can provide a generic bridge, however it will take time due to stability and UX concerns.
We will keep you posted about our decision.

**Comment by iHunterX** [comment]
@Tim-Badin Hello again :D do you have any news with it

**Comment by Miss-PiA** [comment]
Hi @iHunterX,

A new release is plan to be available at the beginning of June, the latest.

Thanks for your interest,
Miss Pia

**Comment by Miss-PiA** [comment]
Hello @iHunterX ,
We released a sample application using Flutter with only basic functionalities, so we can show that our SDK behaves accordingly in this cross-platform implementation. 
We also published a ReadMe with our suggestions. 

Please take a look and know that your feedback will be appreciated!

Best regards,
Miss PiA
