### ISSUE TITLE
MobilePay does not work on iPad

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#31]
**SDK version:**
-  2.1.2
-  have also tried with the latest 2 releases but same issue

**MobilePay App:** 
- Test app 
- App store App 

iOS versions used for testing:
- 14.6
- 14.5
- 14.4
- 14.3

**Problem:**
The app switch does not work on iPad it creates a fullscreen webview inside the app instead.
We have tried both with the test mobilePay app and app store version installed but it gives the same result. 

The app switch works fine on iPhones with the same code.

![Skærmbillede 2021-06-10 kl  13 44 19](https://user-images.githubusercontent.com/71696542/121520325-174b9f80-c9f3-11eb-9865-16d1a8107e55.png)

![A3AD538F-C829-4A7B-AAAF-F0A5216B07C5_1_105_c](https://user-images.githubusercontent.com/71696542/121520288-0bf87400-c9f3-11eb-8e38-79abaf33afb9.jpeg)

**Comment by BuildManager-Nets** [comment]
Hi,

Please try our latest version 2.4.1

This should fix this issue.
