### ISSUE TITLE
Can't modify cardIOButtonTextFont font size

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-iOS-SDK#32]
We are applying custom typography to cardIOButtonTextFont.

However on iOS and Android it does not allow to overwrite its font size. We need to overwrite it to make the button accessible for everyone. The font is a bit small on default.

https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/Classes/NPIInterfaceConfiguration.html#/c:objc(cs)NPIInterfaceConfiguration(py)cardIOButtonTextFont 

Can you make the font size modifiable as well?

**Comment by Nets-LAKA-Mobile-SDK** [comment]
Hi @Waltari10 

Currently it is possible to customize font type but not font size.
We are planning to have a major release after the summer with focus on accessibility wherein (dynamic) custom font size will be supported.

We will keep you posted on availability of this release.
