### ISSUE TITLE
Disable add card with camera functionality

### ISSUE THREAD

**Issue by Waltari10** [Nets-mobile-acceptance/Netaxept-iOS-SDK#33]
We want to disable the camera functionality. Or, at least, we want to make it not default.

Is there anyway to do that? We have gotten customer feedback that it does't work very well.

**Comment by BuildManager-Nets** [comment]
Hi, 

To disable the card scanner feature please refer the `disableCardIO` setting in our documentation 
https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/4-ui-customization.html

However, we do not support changing the default behaviour yet, you can either completely disable the card scanning or go with the current flow.
