### ISSUE TITLE
Camera view is misplaced on iPad after changing orientation

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#34]
Looks to be the same issue that was fixed in 2.2.0  https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/issues/18

![image](https://user-images.githubusercontent.com/71696542/144993311-60956dce-d1a0-4153-8b0c-19c0fe5428c3.png)

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig ,

Thanks for your report! The tablet is unfortunately not supported in the current versions so that UI/UX doesn't adapt to tablet larger screen, but it is on our radar which will be supported in the coming major SDK release v3 in Q1 next year.
