### ISSUE TITLE
Pia.xcframework.zip missing from 2.6.0

### ISSUE THREAD

**Issue by flexund** [Nets-mobile-acceptance/Netaxept-iOS-SDK#36]
In 2.6.0 Pia.xcframework.zip has not been generated for some reason. Is this a mistake or why go back to only provide a "fat" .framework?

**Comment by BuildManager-Nets** [comment]
Hi @felixhedlund ,

Thanks for your report!

You are right and the xcframework zip is available for you to download!

Best regards,
Miss-PiA

**Comment by Miss-PiA** [comment]
Hi @felixhedlund ,

Thanks for your report!

You are right and the xcframework zip is available for you to download!

Best regards,
Miss-PiA

**Comment by flexund** [comment]
Thanks! Would be great if you guys could make a release with this change :) 
@Miss-PiA

**Comment by Miss-PiA** [comment]
Hi @felixhedlund ,

The xcframework has been uploaded in the root of repository here to download https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/blob/master/Pia.xcframework.zip.

**Comment by flexund** [comment]
Yes it is on master, but I assume most clients of this repository like me lock carthage to your releases - in order to not get any surprises by whatever is put on master. And the latest release 2.6.0 is unusable because of the missing .xcframework. 
Thanks again @Miss-PiA

**Comment by Miss-PiA** [comment]
Hi @felixhedlund ,

Would you please elaborate why the Pia.xcframework.zip is unusable? This is the latest release version 2.6.0 which was missing during the release process and added back to same location as usual.

**Comment by flexund** [comment]
It is added on master, not to any release.

For us using this repository it is standard procedure to specify which release to fetch the changes from.

E.g. Cartfile:
`github "Nets-mobile-acceptance/Netaxept-iOS-SDK" ~> 2.6.0`

That release cannot be used because of the missing xcframework on 2.6.0.
It is not standard procedure to fetch anything directly from master because master may change at any point in time. That's why we want your releases to be stable so when we update we'll fetch the latest release.

I'll just wait for your next release then.

**Comment by BuildManager-Nets** [comment]
Hi @felixhedlund ,

Thanks for your clarification! The tag 2.6.0 has been retagged now which includes the latest commit changes. Please kindly have a try again.
