### ISSUE TITLE
The 2.6.0 release can only build for simulator

### ISSUE THREAD

**Issue by flexund** [Nets-mobile-acceptance/Netaxept-iOS-SDK#37]
When building for real device this error occurs:

`truncated fat file. Slice from 115425280 to 173621984 is past end of file with length 87949312 file '[Path-to-DerivedData]/Build/Products/[Build-scheme]/Pia.framework/Pia' for architecture arm64`

Using the provided .xcframework.

This did not happen for previous releases.

**Comment by Miss-PiA** [comment]
Hi @Felix,
2.6.0 is broken please used the 2.6.1.
Thanks & Regards
Miss-PiA

**Comment by flexund** [comment]
2.6.1 works fine, thanks!
