### ISSUE TITLE
Release 2.6.2 is missing the Pia.xcframework

### ISSUE THREAD

**Issue by olafandreas-itf** [Nets-mobile-acceptance/Netaxept-iOS-SDK#39]
Release [2.6.2](https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/tree/2.6.2) does not include the xcframework, this breaks our build pipeline.

This has happened before for release 2.6.0 -> #36 

It seems like you are manually adding the xcframework for every release, and in more than one occasion the file has been missing from the latest release. I would suggest to automate the process of adding the file so that we can rely on the latest release of the xcframework to be included in the SDK.

**Comment by BuildManager-Nets** [comment]
Issue has been fixed now xcframework is available in 2.6.2 release and thanks for your kind suggestion!  We will improve our automation process of xcframework deployment in the future release.
