### ISSUE TITLE
Why is the Pia framework so big?

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-iOS-SDK#4]
122 MB for the Pia file in the Framework is very large to be a framework. What does it contain? 🤔

**Comment by Miss-PiA** [comment]
Hi @henningms 
The framework size is based on two factors:
1. BitCode is enabled, which eventually will decrease your application size when releasing on Store
2. The framework also includes Card.IO library with all C++ dependencies. 

Regards,
- Miss PiA
