### ISSUE TITLE
Card scanning

### ISSUE THREAD

**Issue by Lomaas** [Nets-mobile-acceptance/Netaxept-iOS-SDK#41]
Hello

We are having problems scanning some type of cards and especially the new ones without engraving.
Any reports on this?

Thanks

**Comment by Miss-PiA** [comment]
Hi Lomaas,
Actually, a scanner that we are using has the below limitations.
1. Non-embossed cards cannot be scanned
2. Expiry Date cannot always be scanned
3. Supported card schemes: Visa, MasterCard, American Express (15 digits)
4. Scanner preview is only supported in 640x480 resolution. In any other, the scanner fails to detect the card
In case of any other issues regarding the scanning, please let us know.

Thanks & Regards
