### ISSUE TITLE
3DS windows closed if NEM ID button is pressed

### ISSUE THREAD

**Issue by th-mustache-dk** [Nets-mobile-acceptance/Netaxept-iOS-SDK#42]
We are trying to initiate a tokenized card checkout where we are forcing the use of 3DS

If the NEM-ID option at the bottom of the window is pressed the SDK responds with a cancellation event.

Is this normal procedure? If so how should we handle this?

you can contact me at th(A)mustache.dk for further information.

**Comment by Miss-PiA** [comment]
Hi Mustache,
Could please provide us with a video of the above issue so we can have a proper analysis. 

Thank you

**Comment by th-mustache-dk** [comment]
Hi

Could you contact me via email. I can also send you more detailed logs then.

**Comment by Miss-PiA** [comment]
Hi Mustache,

Is it possible for you to send us details on the **"in-app-support@nets.eu"** id so the issue will be created on the support tool so we can have a detailed discussion on this issue?

Thanks
