### ISSUE TITLE
Card number is scanned and recoqnized using the camera but numbers are not filled in

### ISSUE THREAD

**Issue by th-mustache-dk** [Nets-mobile-acceptance/Netaxept-iOS-SDK#43]
Please contact me at th_at_mustache.dk for a video of the issue.

**Comment by Miss-PiA** [comment]
Hi Mustache,
Thank you for raising the issue.
Is it possible for you to send us details on the **"in-app-support@nets.eu"** id so the issue will be created on the support tool so we can have a detailed discussion on this issue?

Thanks

**Comment by Miss-PiA** [comment]
Hi Mustache,

As there is no reply about the above issue also no email on the above id. So for now we are closing this issue.
Regarding Card Scanner that we are using has limitations 
- Non-embossed cards cannot be scanned
- Expiry Date cannot always be scanned
- Supported card schemes: Visa, MasterCard, American Express (15 digits)
- Scanner preview is only supported in 640x480 resolution. In any other, the scanner fails to detect the card.
We are going to update this information in our coming release.
Also if the above issue is not under this limitation please feel free to report a new issue on GitHub or email us at "in-app-support@nets.eu".

Thanks & Regards
