### ISSUE TITLE
Which is the newest stable release?

### ISSUE THREAD

**Issue by andreas-bakriemer** [Nets-mobile-acceptance/Netaxept-iOS-SDK#45]
The README says version 2.7.0, but the latest actual release is 2.6.1 from January 2022?

**Comment by Miss-PiA** [comment]
@andreas-bakriemer,
The latest updated version is 2.7.0.
Could you please let us know exactly what issue you are facing with the current release?

**Comment by andreas-bakriemer** [comment]
I was merely wondering what the latest stable version was.

Again: The README says version 2.7.0, but the latest actual release is 2.6.1 from January 2022. That made me uncertain as to whether 2.7.0 could be considered stable or not.

**Comment by BuildManager-Nets** [comment]
Hi @andreas-bakriemer ,
The latest supported stable version is v2.7.0. Please give us sometime, we will update actual release detail soon with latest v2.7.0.

Feel free to use v2.7.0 and let us know if you have queries.

Thanks,

**Comment by Miss-PiA** [comment]
Hi @andreas-bakriemer ,
The latest supported stable version is v2.7.0. Please give us sometime, we will update actual release detail soon with latest v2.7.0.

Feel free to use v2.7.0 and let us know if you have queries.

Thanks,
