### ISSUE TITLE
ApplePay payment without importing Pia.sdk library

### ISSUE THREAD

**Issue by adrianmacarenco** [Nets-mobile-acceptance/Netaxept-iOS-SDK#46]
Is it possible to initiate an ApplePay payment without importing Pia.sdk?

We are exploring the App Clip possibilities: specifically ApplePay payment. Given the App Clip size limitation: 10 mb constraints us to not using Pia.sdk.

We are investigating whether or not it is possible to use Netaxept for ApplePay integration without using Pia.sdk.

Currently we support it in our app using Pia.sdk this way:

1. We generate the request for ApplePay using PiaSDK.makeApplePayPaymentRequest.
2. Get `paymentData` calling PiaSDK.netaxeptSOAPPaymentData(from: PKPaymentToken) - having a valid token. Wheres `paymentData` is sent to our server and used to call Netaxept API to finalize the payment. 

For the first step it is pretty straightforward to create a request using the PKPaymentRequest instance on our own.

In regard to the second step, however, it is unclear for us if we could generate locally (mobile side) that `paymentData` output that we currently get from  PiaSDK.netaxeptSOAPPaymentData(from: PKPaymentToken). 

If not, is there a Netaxept API our server could potentially use given that `token` (and maybe some more needed info) ?

**Comment by Miss-PiA** [comment]
Hi Adrian,
 
You can initiate Apple pay without importing the Pia.SDK but only you need to follow the Netaxept instructions on how to send the payment data in the consumable form i.e SOAP.
 
Thanks & Regards

**Comment by Miss-PiA** [comment]
Hi @adrianmacarenco ,

Would you check above comment and confirm whether issue is resolved for you?

Thanks,

**Comment by adrianmacarenco** [comment]
Hey @Miss-PiA ,
Thank you for your reply. I've closed the issue.
