### ISSUE TITLE
Card scanning feature fails a lot

### ISSUE THREAD

**Issue by andreas-bakriemer** [Nets-mobile-acceptance/Netaxept-iOS-SDK#47]
I have tried to use the card scanning feature, but it fails more often than not. It fails in a weird way though: I can clearly see black characters above the scanned images, making it obvious that the card number has been scanned. 

... But when the "Save card" view comes up, the numbers are missing most of the times 😔

**Comment by Miss-PiA** [comment]
Hi @andreas-bakriemer ,

Regarding Card Scanner that we are using has limitations

- Non-embossed cards cannot be scanned
- Card Number / Expiry Date cannot always be scanned
- Supported card schemes: Visa, MasterCard, American Express (15 digits)
- Scanner preview is only supported in 640x480 resolution. In any other, the scanner fails to detect the card.

We are going to update this information in our coming release.
Also if the above issue is not under this limitation please feel free to report a new issue on GitHub or email us at "[in-app-support@nets.eu](mailto:in-app-support@nets.eu)".

Thanks & Regards

**Comment by andreas-bakriemer** [comment]
I think the problem lies elsewhere... As I wrote, I can see that the card is being scanned correctly, but the values are not carried over (from the card io library you use) to the card creation view. I am sorry to say, but I think this SDK uses the card io library in a wrong way, causing the correctly scanned card number to vanish.

**Comment by andreas-bakriemer** [comment]
BTW, this is probably the same issue: https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/issues/43

**Comment by BuildManager-Nets** [comment]
Hi Andreas,
Apologies for the late reply
> I think the problem lies elsewhere... As I wrote, I can see that the card is being scanned correctly, but the values are not carried over (from the cardio library you use) to the card creation view. I am sorry to say, but I think this SDK uses the card io library in the wrong way, causing the correctly scanned card number to vanish.

Could u please provide us more info regarding the issue exactly card no is vanished means when u scanned the card on card view the number is not displayed or it's displaying the wrong number because on our side it is displaying properly.

Thanks

**Comment by andreas-bakriemer** [comment]
I cannot make the card scanner accept a fake card displayed on my computerscreen, and I am not linking to a video of me scanning my own payment card.

Please try this out yourself, I am not exaggerating here: it happens 100% of the time for me. E-V-E-R-Y time... Never ever does this NOT happen:

1. The first time I try to scan a card, the card number is recognised and black numbers are printed on the scanning image - the numbers match my payment card perfectly.
2. When the scanner is closed and I am returned to the card number input, the numbers ARE NOT filled in. I know they were scanned correctly, as I saw them on my screen.
3. When I open the scanner again and scan the same card, the black numbers appear again...
4. This time, the card number is filled in as expected.

I use a Nordea VISA/DK payment card (expiring 05/24), Pia SDK version 2.70, iPhone SE (2020), iOS 16.5

**Comment by BuildManager-Nets** [comment]
Hi Andreas
Thank you for your steps
We will look into it.

Thanks
