### ISSUE TITLE
"Netaxept-iOS-SDK" has no shared framework schemes

### ISSUE THREAD

**Issue by cindyha** [Nets-mobile-acceptance/Netaxept-iOS-SDK#49]
Hi,
I'm using carthage to fetch Netaxept-iOS-SDK. My cartfile has only one line: 
**github "Nets-mobile-acceptance/Netaxept-iOS-SDK"**

 It encountered error like this: 
 _Checking out Netaxept-iOS-SDK at "2.7.0"
*** xcodebuild output can be found in /var/folders/_z/3ql7lkg10vlccq_bx4gvgb4c0000gn/T/carthage-xcodebuild.in0Tf3.log
*** Skipped building Netaxept-iOS-SDK due to the error:
Dependency "Netaxept-iOS-SDK" has no shared framework schemes for any of the platforms: iOS_

Any explanation for this issue would be appreciated!

**Comment by BuildManager-Nets** [comment]
Hi,
Thanking you for reporting we are looking into this issue.
Is this issue happening only on 2.7.0 or also on older versions?

Thanks

**Comment by cindyha** [comment]
> Hi, Thanking you for reporting we are looking into this issue. Is this issue happening only on 2.7.0 or also on older versions?
> 
> Thanks

Hi, its happening on 2.7.0 and previous one 2.6.0 also.

**Comment by BuildManager-Nets** [comment]
Hi Cindya,
Could you please let us know which Carthage version you are using for fetching Netaxept-iOS-SDK?
Also are you able to download the Netaxept-iOS-SDK properly and able to use SDK successfully? 

Thanks

**Comment by cindyha** [comment]
Hi!
Carthage version is 0.39.0.
The sdk was downloaded but failed when trying to build sdk. I supposed to get [Carthage/Build] folder as its documented here when that step is done:
https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

But I got error as below:
![Screenshot 2023-03-08 at 11 39 19](https://user-images.githubusercontent.com/5300207/223691858-26f57c24-a34c-41d9-a766-d9fd20c2a6a7.png)

**Comment by BuildManager-Nets** [comment]
Hi Cindya,
Could you please help us with the below points:-
1. Above screenshot is the mac terminal screenshot is the Carthage folder downloaded in your iOS project.
2. If Yes then are you using  Pia.xcframework from the Netaxept-iOS-SDK folder inside the Carthage folder, which get after unzipping the  Pia.xcframework.zip file?
3. If Yes after integrating the framework into the iOS project what type of error do you get while building it? 

Thanks

**Comment by cindyha** [comment]
> Hi Cindya, Could you please help us with the below points:-
> 
> 1. Above screenshot is the mac terminal screenshot is the Carthage folder downloaded in your iOS project.
> 2. If Yes then are you using  Pia.xcframework from the Netaxept-iOS-SDK folder inside the Carthage folder, which get after unzipping the  Pia.xcframework.zip file?
> 3. If Yes after integrating the framework into the iOS project what type of error do you get while building it?
> 
> Thanks

Hi!
1. Yes
2. From carthage documentation: https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

_On your application targets’ General settings tab, in the Frameworks, Libraries, and Embedded Content section, drag and drop each XCFramework you want to use from the [Carthage/Build](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#carthagebuild) folder on disk._

The XCFramework I should get from Carthage/Build folder which failed to be created when I run command `carthage update --use-xcframeworks` or `carthage update` with error I described : 
**Skipped building Netaxept-iOS-SDK due to the error:
Dependency "Netaxept-iOS-SDK" has no shared framework schemes for any of the platforms: iOS**

So I would like to know why I got that error and why there is no **Build** folder inside **Carthage**, there is only **Checkouts** folder

Thanks!

**Comment by casperriboe** [comment]
@cindyha There is no build folder because Carthage doesn't build a framework. The framework is pre-compiled, that's why it's only in the checkouts. So you should unzip the framework from the zip file in the Checkouts, then drag the framework into Xcode. Carthage expects a framework or something to compile, but instead it sees a zip file, that's why it cannot find anything.
Using Carthage is kinda pointless since you will do the same thing if you download the SDK manually. Carthage is just a glorified download method at that point.

**Comment by BuildManager-Nets** [comment]
Thank you @casperriboe for your reply on the build folder.
Apologies for the late reply @cindyha 
One thing just wants to confirm are u able to use **Pia.xcframework** in your application or are you facing some issues with any type of blocker while using SDK?

Thanks

**Comment by cindyha** [comment]
> @cindyha There is no build folder because Carthage doesn't build a framework. The framework is pre-compiled, that's why it's only in the checkouts. So you should unzip the framework from the zip file in the Checkouts, then drag the framework into Xcode. Carthage expects a framework or something to compile, but instead it sees a zip file, that's why it cannot find anything. Using Carthage is kinda pointless since you will do the same thing if you download the SDK manually. Carthage is just a glorified download method at that point.

Thank you so much! I did what you told, can run the app nicely. You are right about Carthage. I was expecting it would help me to do all that instead of me doing it manually :))

**Comment by cindyha** [comment]
> Thank you @casperriboe for your reply on the build folder. Apologies for the late reply @cindyha One thing just wants to confirm are u able to use **Pia.xcframework** in your application or are you facing some issues with any type of blocker while using SDK?
> 
> Thanks

Hi, its working fine now. Thanks!

**Comment by BuildManager-Nets** [comment]
Hi @cindyha,

Thank you for confirming things are working on your side.
The scheme and building part will get updated in a future release.
For now, we are closing this ticket and in case of any issues you can create a new ticket for the same.

Thanks & Regard.
