### ISSUE TITLE
Make available as a CocoaPod

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-iOS-SDK#5]
Is it possible to make the framework available as a CocoaPod? 

Thanks!

**Comment by Miss-PiA** [comment]
Hi @henningms 
Currently, the framework is closed-source, hence it's not possible to make it available for Cocoapods. We are sorry for any inconvenience.

Regards,
- Miss PiA

**Comment by nfrydenholm** [comment]
@Miss-PiA have you tried to look into closed-source distribution using Cocoapods?
According to these blog posts, it doesn't seem to be impossible.
https://medium.com/@mkeremkeskin/distributing-closed-source-frameworks-with-cocoapods-and-carthage-44fd141cfd78 

https://www.tirupatibalan.com/2019/01/10/publish-closed-source-framework-cocoapods-ios.html

**Comment by mortenholmgaard** [comment]
@Miss-PiA Please look into the above
