### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by sbo-nemlig** [Nets-mobile-acceptance/Netaxept-iOS-SDK#53]
Will your SDK have a privacy manifest before Apples deadline spring 2024 

https://developer.apple.com/news/?id=r1henawx

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig,

Thank you for highlight this issue. We are now collecting all information to provide proper entry for privacy manifest. Soon we will get back with updated SDK.

**Comment by Miss-PiA** [comment]
Hi @sbo-nemlig,

we already scheduled a patch release in February to fulfill Apple requirements. We are open to close cooperation to make sure our SDK meet all requirements and you experience smooth review process. We will notify you once new SDK version in out.

**Comment by sbo-nemlig** [comment]
Super thx

**Comment by Miss-PiA** [comment]
Privacy manifest and Code Signature has been added to XCFramework in latest release 2.7.3. We are closing this issue, thank you for your contribution!
