### ISSUE TITLE
Can not finish the 3DS webview (Nextaxept iOS SDK + Flutter)

### ISSUE THREAD

**Issue by cimsunf0702** [Nets-mobile-acceptance/Netaxept-iOS-SDK#6]
Hi guys,
I'm integrating Nextaxept-ios-SDK to my app (Flutter using Platform channel). I'm following the steps in this flow: https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/blob/master/Documentation/img/Basic%20Payment%20Flow.png

But I'm stucked in the step when the "Redirected to 3DS web page". The webpage are displayed, but when I press the "next" button, there's no changes or navigation. 

Does anybody have the same issue and give me some suggestions.
Thank you !
![3DS webpage](https://user-images.githubusercontent.com/17775289/61515880-daa4e280-aa2d-11e9-8a03-a716e4413e2b.png)

**Comment by cimsunf0702** [comment]
> Hi guys,
> I'm integrating Nextaxept-ios-SDK to my app (Flutter using Platform channel). I'm following the steps in this flow: https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/blob/master/Documentation/img/Basic%20Payment%20Flow.png
> 
> But I'm stucked in the step when the "Redirected to 3DS web page". The webpage are displayed, but when I press the "next" button, there's no changes or navigation.
> 
> Does anybody have the same issue and give me some suggestions.
> Thank you !

**Comment by Miss-PiA** [comment]
Hello,

If possible please share the sample request that you are doing the register call with, so we can try to replicate the issue and provide a solution.

Thank you

**Comment by Miss-PiA** [comment]
Hello,

If you could let us know which "serviceType" are you using for the register call ?

Thank you

**Comment by cimsunf0702** [comment]
Hi, 
We're using serviceType 'M' - Merchant Hosted
Thank you !

**Comment by cimsunf0702** [comment]
Hi, 
And the sample request we're using: 
![sample](https://user-images.githubusercontent.com/17775289/61613526-c2320380-ac8b-11e9-9731-dc59776af6b5.png)
Thank you.

**Comment by Miss-PiA** [comment]
Hello,

Please have a look at our FAQ section
https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/blob/master/FAQs.md

If still you are not able to resolve the issue, let us know.

Thank you.

**Comment by cimsunf0702** [comment]
Hi Miss-PiA, 
- You're correct, After checked and updated our registration + used another test card  -> The process is complete with success

Thank you very much for your support !

**Comment by Miss-PiA** [comment]
> Hi Miss-PiA,
> 
> * You're correct, After checked and updated our registration + used another test card  -> The process is complete with success
> 
> Thank you very much for your support !

**Comment by Miss-PiA** [comment]
Hello,

Good to know the issue is resolved.

Any other issue let us know, we are happy to help.

Thanks you
