### ISSUE TITLE
iOS13: Crash when presenting payment view 

### ISSUE THREAD

**Issue by jakobmygind** [Nets-mobile-acceptance/Netaxept-iOS-SDK#7]
When presenting PiaController the app crashes with this message:

"App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead"

Happens in example project as well.

I realize this iOS13 is still in beta, but I just wanted to give heads up to make sure it's fixed as soon as iOS13 is released.

**Comment by Miss-PiA** [comment]
Hello @jakobmygind 

Thank you for the heads up.
We will be making changes in our implementation to be on par with latest apple guidelines.

**Comment by jakobmygind** [comment]
@Miss-PiA Ok, thanks, to clarify, it's when building with the iOS 13 SDK, not just running on iOS 13 device

**Comment by henningms** [comment]
Hi there, we're experiencing the same issue. Do you have an ETA on when we can expect a new release? :) Thanks!

**Comment by Miss-PiA** [comment]
Hello @henningms , sorry for the inconvenience. We are working the issue and let you know when it is fixed and ready to release.
Thank you

**Comment by henningms** [comment]
How's it going? :D 

iOS 13 is set to release 19th september

**Comment by Miss-PiA** [comment]
The issues is resolved. Please use the latest V1.4.0 of the SDK

**Comment by jakobmygind** [comment]
@Miss-PiA Can you please take a look at

https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/issues/9

It's a week old and no comments.
